package Exceptions.throw_throws;

public class Main {
}
